### PR TITLE
Get more than one attribute value

### PR DESCRIPTION
**Pull request by StuBez**
I need to be able to get all values of an attribute for something I'm working on but noticed that LdapEntry::get() only returns the first.

I've kept the functionality of LdapEntry::get() to return only the first element to stop any BC breaks but added LdapEntry::getFirst() and LdapEntry::getAll().

I'm not completely happy with the method names so feel free to change them if you're happy to merge this.

### CODE REVIEW

**Comment by gossi** [comment]
Yes, I see the need and this should be baked into the lib. So, I'm also not that happy about the naming. Another thing, that looks similar to first and all entries is in LdapResult, which I'm likely happy to implement the Iterator Interface (http://php.net/manual/en/class.iterator.php) to make it easily loopable with the foreach construct:

```
$result = $ldap->search(...);

foreach ($result as $entry) {
    // do something here
}
```

The question is, does it makes sense to have something similar for attributes? Like a class LdapAttribute that implements the iterator interface? Only for interna, the api should stay as simple as it is right now. The first thing here is the api and how to use it then the code for it.

Some examples:

```
$entry->has('mail');
$entry->count('mail');

foreach($entry->iter('mail') as $mail) {
    echo $mail; // or
    echo $mail->getValue()
}

echo $entry->get('mail', 2); // getting the mail attribute at the third position? introducing an optional second param

print_r($entry->assoc('mail'));
```

Would love to hear some feedback on it.

Thanks
gossi

**Comment by gossi** [comment]
The better question of course is: How would you like to use the library?

**Comment by StuBez** [comment]
I'm currently just iterating through the results so implementing an Iterator interface would be ideal. It would also be helpful to have has() and count() methods. I'm not at work to see exactly how this would fit for my purposes but I will do so on Monday.

I think I like all of your suggestions but passing a parameter to get a particular attribute value doesn't seem as elegant as the rest. I don't have a use case for being able to do this so I can't think of a better way of doing it, though. Perhaps it may not be required?

**Comment by StuBez** [comment]
I don't have any additional requirements above the features you suggested but the has() method would be really useful. My only question is whether you can think of a way to find out whether an attribute value exists without a warning being thrown by php_ldap?

**Comment by gossi** [comment]
Hey Stuart,

I recently thought about the LdapEntry class and how to refactor it, with your feature request in mind. One thing that I have loved to use lately is the ActiveRecord pattern for ORMs. So I think this is a neat integration here. As so, the ActiveRecord pattern uses strict getter and setter and I also think this can be burrowed down, because the rest of the lib doesn't work like that (bit of jquery-like here).

So, instead of having a modify() and add() method, this can be made into one, and the lib decides wether to add or modify it, some like this:

```
$entry->has('attr');
$entry->count('attr');
$entry->attr('mail'); // get attribute at index 0 
$entry->attr('mail', 'test@mail.com'); // setter
$entry->delete('mail');
```

The thing is, this is working very well with only one attribute (the attr() method). So, maybe attrs for multiple values?

```
$entry->attrs('mail'); // get all attributes
$entry->attrs('mail', 'test@mail.com'); // what happens here? Replace the first one, add this one?
```

The other thing is from a developer perspective you cannot be sure, if a specific attribute you work with has multiple values. 

One API to rule them all here? I'm happy for suggestions.

**Comment by gossi** [comment]
Oh maybe this one:

```
$entry->attr('mail'); // get attribute at index 0 
$entry->attr('mail', 'test@mail.com'); // setter
$entry->attr('mail', 'test@mail.com', 1); // setter at index 1
$entry->attrs('mail'); // get all attributes
$entry->attrs('mail', 1); // gets an attribute at index 1
```

What do you think?

**Comment by StuBez** [comment]
I haven't done anything with LDAP for a few months but that seems like it would work.

My only concern is that it could be difficult to remember which method calls would result in a get and which would be a set.

**Pull request closed without merging**
